name: passprox
base: core18
adopt-info: detect-version
summary: The proxy HAProxy inside a snap
description: |
  HAProxy with a bundled certbot. More or less a vanilla install with automatic reloads.
  
  Install it and edit $SNAP_DATA/haproxy.cfg. HAProxy will be reloaded automatically
  if the file is valid.

grade: stable
confinement: strict

apps:
  passprox:
    command: echo "Usage instructions at https://github.com/nsg/passprox"

  haproxy:
    command: bin/haproxy -W -f $SNAP_DATA/haproxy.cfg -p /etc/haproxy/haproxy.pid
    adapter: full
    daemon: simple
    passthrough:
      restart-condition: always
      restart-delay: 5s
    plugs:
      - network-bind
      - network

  certbot:
    command: bin/certbot-wrapper
    adapter: full
    plugs:
      - network

  reload:
    command: bin/reload
    adapter: full
    plugs:
      - network

  refresh-certs:
    command: bin/refresh-certs
    adapter: full
    daemon: simple
    passthrough:
      timer: 00:00-24:00/2
    plugs:
      - network-bind
      - network

  watch:
    command: bin/reload-service
    daemon: simple
    adapter: full
    plugs:
      - network

hooks:
  post-refresh:
    plugs:
      - network
  configure:
    plugs:
      - network-bind
      - network

layout:
  /etc/haproxy:
    type: tmpfs

parts:
  detect-version:
    plugin: nil
    override-build: |
      apt -y install jq curl
      VERSION_TAG=$(git ls-remote --tags --sort v:refname --refs http://git.haproxy.org/git/haproxy-2.3.git/ | awk -F'/' '{ print $NF }' | grep -E '^v[0-9]\.[0-9]+\.[0-9]+$' | sort | tail -1)
      snapcraftctl set-version ${VERSION_TAG/v/}

  haproxy:
    # Also update the version url above in detect-version
    source: http://git.haproxy.org/git/haproxy-2.3.git
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    plugin: make
    make-parameters:
      - TARGET=linux-glibc
      - USE_OPENSSL=1
      - USE_ZLIB=1
      - USE_PCRE=1
      - USE_LUA=1
    build-packages:
      - build-essential
      - libssl-dev
      - libpcre3-dev
      - libz-dev
    stage:
      - -usr/local/doc
      - -usr/local/share
    organize:
      usr/local/sbin/haproxy: bin/haproxy
    after: [ lua, detect-version ]

  scripts:
    source: scripts
    plugin: dump
    stage-packages:
      - inotify-tools
      - certbot
      - curl
    stage:
      - -usr/share/man
      - -usr/share/doc
    organize:
      'reload': bin/
      'reload-service': bin/
      'refresh-certs': bin/
      'cat-certs': bin/
      'certbot-wrapper': bin/

  lua:
    source: https://www.lua.org/ftp/lua-5.3.6.tar.gz
    plugin: make
    override-build: |
      make linux
      make
      make install INSTALL_TOP=/usr/local
    build-packages:
      - libreadline-dev
