name: passprox
base: core18
version: 2.3.2
summary: The proxy HAProxy inside a snap
description: |
  HAProxy with a bundled certbot. More or less a vanilla install with automatic reloads.
  
  Install it and edit $SNAP_DATA/haproxy.cfg. HAProxy will be reloaded automatically
  if the file is valid.

grade: stable
confinement: strict

apps:
  passprox:
    command: echo "Usage instructions at https://github.com/nsg/passprox"

  haproxy:
    command: bin/haproxy -W -f $SNAP_DATA/haproxy.cfg -p /etc/haproxy/haproxy.pid
    adapter: full
    daemon: simple
    passthrough:
      restart-condition: always
      restart-delay: 5s
    plugs:
      - network-bind
      - network

  certbot:
    command: bin/certbot-wrapper
    adapter: full
    plugs:
      - network

  reload:
    command: bin/reload
    adapter: full
    plugs:
      - network

  refresh-certs:
    command: bin/refresh-certs
    adapter: full
    daemon: simple
    passthrough:
      timer: 00:00-24:00/2
    plugs:
      - network-bind
      - network

  watch:
    command: bin/reload-service
    daemon: simple
    adapter: full
    plugs:
      - network

  graphite:
    command: bin/haproxy-graphite.py
    daemon: simple
    adapter: full
    after: [haproxy]

    plugs:
      - network

hooks:
  post-refresh:
    plugs:
      - network
  configure:
    plugs:
      - network-bind
      - network

layout:
  /etc/haproxy:
    type: tmpfs

parts:
  haproxy:
    source: http://git.haproxy.org/git/haproxy-2.3.git #haproxy-source-marker
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    plugin: make
    make-parameters:
      - TARGET=linux-glibc
      - USE_OPENSSL=1
      - USE_ZLIB=1
      - USE_PCRE=1
      - USE_LUA=1
    build-packages:
      - build-essential
      - libssl-dev
      - libpcre3-dev
      - libz-dev
    stage:
      - -usr/local/doc
      - -usr/local/share
    organize:
      usr/local/sbin/haproxy: bin/haproxy
    after: [ lua ]

  scripts:
    source: scripts
    plugin: dump
    stage-packages:
      - inotify-tools
      - certbot
      - curl
    stage:
      - -usr/share/man
      - -usr/share/doc
    organize:
      'reload': bin/
      'reload-service': bin/
      'refresh-certs': bin/
      'cat-certs': bin/
      'certbot-wrapper': bin/

  haproxy-graphite:
    source: haproxy-graphite
    plugin: python
    python-packages:
      - requests
    override-build: |
      install haproxy-graphite.py -D $SNAPCRAFT_PART_INSTALL/bin/haproxy-graphite.py

  lua:
    source: https://www.lua.org/ftp/lua-5.3.6.tar.gz
    plugin: make
    override-build: |
      make linux
      make
      make install INSTALL_TOP=/usr/local
    build-packages:
      - libreadline-dev
