name: passprox
base: core18
version: '2.0.1'
summary: The proxy HAProxy inside a snap
description: |
  More or less a vanilla HAProxy install with automatic reloads.
  
  Install it and edit $SNAP_DATA/haproxy.cfg. HAProxy will be reloaded automatically
  if the file is valid.

grade: stable
confinement: strict

apps:
  passprox:
    command: bin/haproxy -W -f $SNAP_DATA/haproxy.cfg -p /etc/haproxy/haproxy.pid
    adapter: full
    daemon: simple
    plugs:
      - network-bind
      - network

  reload:
    command: bin/reload
    adapter: full
    plugs:
      - network

  refresh-certs:
    command: bin/refresh-certs
    adapter: full
    plugs:
      - network

  watch:
    command: bin/reload-service
    daemon: simple
    adapter: full
    plugs:
      - network

hooks:
  post-refresh:
    plugs:
      - network

layout:
  /etc/haproxy:
    type: tmpfs

parts:
  haproxy:
    source: http://git.haproxy.org/git/haproxy-2.0.git
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    plugin: make
    make-parameters:
      - TARGET=linux-glibc
      - USE_OPENSSL=1
      - USE_ZLIB=1
      - USE_PCRE=1
      - USE_LUA=1
    build-packages:
      - build-essential
      - libssl-dev
      - libpcre3-dev
      - libz-dev
    stage:
      - -usr/local/doc
      - -usr/local/share
    organize:
      usr/local/sbin/haproxy: bin/haproxy
    after: [ lua ]

  scripts:
    source: scripts
    plugin: dump
    stage-packages:
      - inotify-tools
      - certbot
      - curl
    stage:
      - -usr/share/man
      - -usr/share/doc
    organize:
      'reload': bin/
      'reload-service': bin/
      'refresh-certs': bin/

  lets-encrypt-x3-cert:
    plugin: nil
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/etc/certs/
      wget https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem.txt \
        -O $SNAPCRAFT_PART_INSTALL/etc/certs/lets-encrypt-x3-cross-signed.pem
    build-packages:
      - wget

  lua:
    source: https://www.lua.org/ftp/lua-5.3.5.tar.gz
    plugin: make
    override-build: |
      make linux
      make
      make install INSTALL_TOP=/usr/local
    build-packages:
      - libreadline-dev
